### ISSUE TITLE
Create score system

### ISSUE THREAD

**Issue by shaypheraddison** [resoluteCoder/pysnake#11]
Count 1 every time food is eaten by snake.
Store score into variable to save for high score.

**Comment by resoluteCoder** [comment]
This issue should also add the ability to see the score on the screen

**Comment by resoluteCoder** [comment]
The last PR I believe 14. Set the foundation but let's add the ability for the user to see the score and it being updated every time the snake eats the food

**Comment by shaypheraddison** [comment]
That was my next goal to do. Just wanted to get the scoring working first.

**Comment by shaypheraddison** [comment]
added scoring system and has score displayed. count increases each time the food is eaten

fixes #11
