### ISSUE TITLE
Bug for collision between food and snake

### ISSUE THREAD

**Issue by resoluteCoder** [resoluteCoder/pysnake#13]
The collision between food and snake does not work consistently. Sometimes it detects only on the top left corner, correctly, and not at all.

**Comment by shaypheraddison** [comment]
So far, after testing, it seems to be colliding on all sides, but the snake needs to be about halfway into the food to count the collision. Are we wanting it to collide and count the collision at the edge of each side of the food ?

**Comment by resoluteCoder** [comment]
Yes whatever side(edge) the snake collides into, the food should disappear

**Comment by shaypheraddison** [comment]
corrected the collision of the food. now snake does not go halfway through the food for the collision to be detected.

Fixes #13
