### ISSUE TITLE
add the ability to have collision between the food and snake

### ISSUE THREAD

**Issue by resoluteCoder** [resoluteCoder/pysnake#8]
When the snake and the food collide have the snake grow larger and the food randomize to a new location

**Comment by shaypheraddison** [comment]
have you pushed your code to the repo for the collision? I think my scoring system I am working on needs it for the collision block

**Comment by resoluteCoder** [comment]
For the integration part yes it would need the collision but for implementing the score system. You should be able to create it without the collision. I'm going to push what I have with the collision. 

Feel free to tweak the oddities with the collision
